-- V1: USERS table matching co.com.practica.auth.entity.User
-- Portable SQL intended for PostgreSQL (prod). Flyway is disabled in dev/test (H2 + Hibernate).

CREATE TABLE USERS (
    ID                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME                    VARCHAR(50)  NOT NULL,
    PASSWORD_HASH               VARCHAR(255) NOT NULL,
    FULL_NAME                   VARCHAR(100) NOT NULL,
    EMAIL                       VARCHAR(100) NOT NULL,
    ROLE                        VARCHAR(20)  NOT NULL,
    MASTER_TOKEN                TEXT,
    SESSION_TOKEN               TEXT,
    SESSION_UUID                VARCHAR(36),
    STATUS                      VARCHAR(1)   NOT NULL DEFAULT 'A',
    CREATED_AT                  TIMESTAMP    NOT NULL,
    LAST_LOGIN_AT               TIMESTAMP,
    SESSION_TOKEN_EXPIRES_AT    TIMESTAMP,
    FAILED_LOGIN_ATTEMPTS       INTEGER      NOT NULL DEFAULT 0,
    LOCKED_UNTIL                TIMESTAMP,
    CONSTRAINT UK_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UK_USERS_EMAIL UNIQUE (EMAIL)
);

CREATE INDEX IDX_USERS_SESSION_UUID ON USERS (SESSION_UUID);
