-- Module tag on permissions (e.g. INVENTARIO, PARAMETROS, RBAC)
ALTER TABLE PERMISSIONS ADD COLUMN IF NOT EXISTS MODULE VARCHAR(50);

UPDATE PERMISSIONS SET MODULE = 'PARAMETROS' WHERE CODE LIKE 'PARAMETRO_%' AND MODULE IS NULL;
UPDATE PERMISSIONS SET MODULE = 'RBAC' WHERE CODE IN ('USER_ADMIN', 'GROUP_ADMIN', 'DIRECTORY_READ') AND MODULE IS NULL;
UPDATE PERMISSIONS SET MODULE = 'CORE' WHERE MODULE IS NULL;

CREATE INDEX IF NOT EXISTS IDX_PERMISSIONS_MODULE ON PERMISSIONS (MODULE);
